// packages/example/app/page.tsx
/** @jsxImportSource next-yak */
import { YakThemeProvider, atoms, css, styled } from "next-yak";
import styles from "./page.module.css";
import { queries, colors } from "@/theme/constants.yak";
import { Clock } from "./Clock";
import { Inputs } from "@/app/Input";
import { HighContrastToggle } from "./HighContrastToggle";
import { typography } from "./mixins";
import "./global.css";

const headline = css<{ $primary?: boolean }>`
  ${typography.h1};
  filter: drop-shadow(0px 0px 1px #fff);
  ${({ theme }) =>
    theme.highContrast
      ? css`
          color: ${colors.dark};
        `
      : css`
          color: blue;
          background: linear-gradient(
            149deg,
            #ae52eb 0%,
            rgba(253, 29, 29, 1) 50%,
            rgba(252, 176, 69, 1) 100%
          );
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        `}

  ${queries.sm} {
    font-size: 1.5rem;
    ${({ $primary }) =>
      $primary &&
      css`
        font-size: 1.7rem;
      `}
  }

  &:before,
  &:after {
    content: "\\2022";
  }

  &:hover {
    color: red;
  }
  ${({ $primary }) =>
    $primary &&
    css`
      color: green;
    `}
`;

const Headline = styled.h1<{ $primary?: boolean }>`
  ${headline}
`;

const SubHeadline = styled.h2`
  ${typography.h2};
  color: #323248;
`;

const Button = styled.button<{ $primary?: boolean }>`
  @layer base {
    display: block;
    ${({ theme }) =>
      theme.highContrast
        ? css`
            color: ${colors.dark};
          `
        : css`
            color: #009688;
          `}
    background: #fff;
  }
  border: 1px solid currentColor;
  font-size: 17px;
  padding: 7px 12px;
  font-weight: normal;
  margin: 6px 0;
  margin-right: 12px;
  display: inline-block;
  font-family: "Open Sans", sans-serif;
  min-width: 120px;
  ${({ $primary }) =>
    $primary &&
    css`
      border-width: 2px;
    `}
`;

const FancyButton = styled(Button)`
  color: #fff;
  background: linear-gradient(
    149deg,
    #ae52eb 0%,
    rgba(253, 29, 29, 1) 50%,
    rgba(252, 176, 69, 1) 100%
  );
`;

const StyledLink = styled.a`
  background: linear-gradient(
    149deg,
    #ae52eb 0%,
    rgba(253, 29, 29, 1) 50%,
    rgba(252, 176, 69, 1) 100%
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-size: 200% 100%;
  filter: drop-shadow(0px 0px 1px #fff);
  font-weight: bold;
  border-bottom: 2px solid red;
  transition: all 0.3s ease-in-out;
  &:hover {
    background-position: 100% 0;
    border-bottom-color: #9d0a0a;
  }
`;

export default function Home() {
  return (
    <YakThemeProvider>
      <main className={styles.main}>
        <Headline $primary>Hello world</Headline>
        <SubHeadline>example page</SubHeadline>
        <Button>Ghost</Button>
        <Button $primary>Primary Ghost</Button>
        <FancyButton $primary title="fancy">
          Fancy Ghost
        </FancyButton>
        <Clock />
        <HighContrastToggle />
        <StyledLink href="https://github.com/jantimon/next-yak/tree/main/packages/example/app">
          view code
        </StyledLink>
        <p
          css={css`
            color: green;
          `}
        >
          CSS Prop works if this is green
        </p>
        <p
          css={css`
            color: red;
            ${() =>
              true &&
              css`
                color: green;
              `}
          `}
        >
          Conditional CSS Prop works if this is green
        </p>
        <p
          css={css`
            color: violet;
          `}
        >
          Nested CSS Prop works
          <span
            css={css`
              color: green;
            `}
          >
            {" "}
            if this is green{" "}
          </span>
          and this is violet
        </p>
        <p css={atoms("salmon")}>
          Atoms in css props work if this is <span>salmon</span>
          <span css={atoms("salmon", true && "indigo")}>
            {" "}
            and this is indigo
          </span>{" "}
        </p>
        <Inputs />
      </main>
    </YakThemeProvider>
  );
}

// examples/vite-solid/src/App.tsx
import { css, keyframes, styled } from "@yak/solid";
import { createSignal } from "solid-js";
import { Clock } from "./Clock.tsx";
import { HighContrastToggle } from "./HighContrastToggle.tsx";

const Headline = styled.h1<{ $primary?: boolean }>`
  filter: drop-shadow(0px 0px 1px #fff);
  ${(props) =>
    props.theme().highContrast
      ? css`
          color: #000;
        `
      : css`
          color: blue;
          background: linear-gradient(
            149deg,
            #ae52eb 0%,
            rgba(253, 29, 29, 1) 50%,
            rgba(252, 176, 69, 1) 100%
          );
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        `}

  &:hover {
    color: red;
  }
  ${(props) =>
    props.$primary &&
    css`
      font-size: 2.4rem;
    `}
`;

const Button = styled.button<{ $primary?: boolean }>`
  display: inline-block;
  ${(props) =>
    props.theme().highContrast
      ? css`
          color: #000;
        `
      : css`
          color: #009688;
        `}
  background: #fff;
  border: 1px solid currentColor;
  font-size: 17px;
  padding: 7px 12px;
  margin: 6px 12px 6px 0;
  min-width: 120px;
  ${(props) =>
    props.$primary &&
    css`
      border-width: 2px;
    `}
`;

const FancyButton = styled(Button)`
  color: #fff;
  background: linear-gradient(
    149deg,
    #5552eb 0%,
    rgba(253, 29, 29, 1) 50%,
    rgba(252, 176, 69, 1) 100%
  );
`;

const SubmitButton = styled(Button).attrs({ type: "submit" })`
  font-weight: bold;
`;

const rotate = keyframes`
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
`;

const Spinner = styled.div`
  width: 24px;
  height: 24px;
  display: inline-block;
  border-radius: 50%;
  border: 3px solid #ddd;
  border-top-color: #ae52eb;
  animation: ${rotate} 1.2s linear infinite;
`;

const Progress = styled.div<{ $percent: number }>`
  height: 8px;
  margin: 12px 0;
  border-radius: 4px;
  background: #e5e5ef;
  overflow: hidden;

  &::before {
    content: "";
    display: block;
    height: 100%;
    background: #009688;
    width: ${(props) => props.$percent}%;
    transition: width 0.2s ease-out;
  }
`;

function App() {
  const [percent, setPercent] = createSignal(30);
  return (
    <main>
      <Headline $primary>Yak + Solid 2</Headline>
      <Clock />
      <HighContrastToggle />
      <Button>Ghost</Button>
      <Button $primary>Primary Ghost</Button>
      <FancyButton $primary title="fancy">
        Fancy Ghost
      </FancyButton>
      <SubmitButton>Submit (attrs)</SubmitButton>
      <p>
        <Spinner /> keyframes work if this spins
      </p>
      <Progress $percent={percent()} />
      <Button onClick={() => setPercent((current) => (current + 10) % 110)}>
        Grow progress bar ({percent()}%)
      </Button>
      <p
        css={css`
          color: green;
        `}
      >
        CSS Prop works if this is green
      </p>
      <p
        class="static-class"
        css={css`
          color: red;
          ${() =>
            true &&
            css`
              color: green;
            `}
        `}
      >
        Conditional CSS Prop works if this is green
      </p>
    </main>
  );
}

export default App;
